---
- name: install tomcat
  hosts: all  
  become: true

  tasks:
  - name: create directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
      owner: root
      group: root

  #- name: install tomcat
  #  get_url:
  #      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.89/bin/apache-tomcat-9.0.89.tar.gz
  #      dest: /opt/tomcat
  #      mode: 0755 


  - name: uninstall tomcat
    file:
        path: /opt/tomcat
        state: absent