---
- name: touching a file
  hosts: ws
  become:

  tasks:
   - name: creating a file
     file: 
      path: /home/ec2-user/file1
      state: touch

   - name: adding content to file
     lineinfile:
      path: /home/ec2-user/file1
      regexp: '^we are going to succeed'
      insertafter: '^#we are going to make 6 figures'
      line: 'success'
