---
- name: Update all packages on servers
  hosts: all
  become: yes
  tasks:
    - name: Update packages on Debian
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Update packages on RedHat
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"