pipeline {
    agent {
        label 'ansible label'
    }
    triggers {
        cron('0 0 1 * *')
    }
    stages {
        stage('run a cronjob every month') {
            steps {
                dir('/home/ec2-user/ansible-dev/Ansible-project/cronjob') {
                    sh 'ansible-playbook cronjob.yml'
                }
            }
        }
    }
}
